language: c
sudo: required

os:
- linux
- osx

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

env:
  global:
  - EXTRA_REMOTES="https://coq.inria.fr/opam/core-dev"
  - OPAMJOBS=2
  - OCAML_VERSION=4.05

script: curl -L https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh | sh

before_cache:
- if [ $TRAVIS_OS_NAME = osx ]; then brew cleanup; fi
- rm -rf $HOME/.opam/log

cache:
  directories:
  - $HOME/.opam
  - $HOME/Library/Caches/Homebrew
